- id: '1668202384144'
  alias: Notify Machine terminé
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.status_machine_a_laver
    from:
    to: Terminé
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target: media_player.echo_dot_bureau, media_player.echo_dot_salon
      message: La machine à laver est terminé
  - service: tts.google_translate_say
    data:
      cache: false
      entity_id: media_player.cuisine
      message: La machine à laver est terminée
      language: fr
  - service: notify.mobile_app_iphone_de_loic
    data:
      message: La machine à laver est terminée
      title: La machine à laver est terminé
  - service: notify.hass_agent_device
    data:
      message: La machine à laver est terminé
  - service: notify.mobile_app_iphone_de_emma
    data:
      message: La machine à laver est terminé
      title: La machine à laver est terminé
  mode: single
- id: '1668202826223'
  alias: Notify - Washing Machine Emptied action
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: MACHINE_EMPTIED
  condition: []
  action:
  - service: notify.mobile_app_iphone_loic
    data:
      message: clear_notification
      data:
        tag: washing
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.machine_a_laver_videe
  mode: single
- id: '1669882300981'
  alias: Set - Washing Machine States
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.prise_tuya_power
    id: machine-finished
    for:
      hours: 0
      minutes: 5
      seconds: 0
    attribute: power
    below: 2
  - platform: numeric_state
    entity_id: sensor.prise_tuya_power
    id: machine-running
    attribute: power
    above: 2
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - machine-finished
      sequence:
      - service: input_select.select_option
        data:
          option: Terminé
        target:
          entity_id: input_select.status_machine_a_laver
    - conditions:
      - condition: trigger
        id: machine-running
      sequence:
      - service: input_select.select_option
        data:
          option: En cours
        target:
          entity_id: input_select.status_machine_a_laver
  mode: single
- id: '1688855930899'
  alias: 'Turn off Clim '
  description: ''
  trigger:
  - type: temperature
    platform: device
    device_id: 671fa9ec950eb3ad693ce0265811ab0e
    entity_id: sensor.chambre_temperature
    domain: sensor
    below: 24
    above: 17
  condition:
  - type: is_temperature
    condition: device
    device_id: 671fa9ec950eb3ad693ce0265811ab0e
    entity_id: sensor.chambre_temperature
    domain: sensor
    below: 23
    above: 17
  action:
  - device_id: acfeded08b99c8275ab445040415db85
    domain: climate
    entity_id: climate.forceclima
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1688856041173'
  alias: auto clim
  description: ''
  trigger:
  - platform: device
    device_id: 671fa9ec950eb3ad693ce0265811ab0e
    domain: climate
    entity_id: climate.smart_radiator_thermostat_chambre
    type: current_temperature_changed
    above: 25
  condition:
  - condition: time
    after: 00:00:00
    before: '11:00:00'
  action:
  - device_id: acfeded08b99c8275ab445040415db85
    domain: climate
    entity_id: climate.forceclima
    type: set_hvac_mode
    hvac_mode: cool
  mode: single
- id: '1690408049218'
  alias: Lance Retrobat
  description: ''
  trigger: []
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.launchretrobat
  mode: single
- id: '1713253703491'
  alias: 'Commute - Update Loïc '
  description: ''
  triggers:
  - minutes: /5
    trigger: time_pattern
  conditions:
  - condition: time
    after: 08:00:00
    before: '11:00:00'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - target:
      entity_id: sensor.trajet_travail_loic
    data:
      entity_id:
      - sensor.trajet_travail_loic
    action: homeassistant.update_entity
  mode: single
- id: '1750148816007'
  alias: 'Commute - Update Emma '
  description: ''
  triggers:
  - minutes: /5
    trigger: time_pattern
  conditions:
  - condition: time
    after: 06:00:00
    before: 09:00:00
  - condition: time
    weekday:
    - wed
    - thu
    - fri
    - sat
  actions:
  - target:
      entity_id: sensor.trajet_travail_emma
    data:
      entity_id:
      - sensor.trajet_travail_emma
    action: homeassistant.update_entity
  mode: single
